name: Sync Pages to Void Tech Repository
"on":
  push:
    paths:
      - pages/**
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Clone Target Repository
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git clone https://${API_TOKEN_GITHUB}@github.com/cozy-creator/void-tech.git
          cd void-tech
          git checkout dev

      - name: Copy Files to Target Repository Folder
        env:
          PAT: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          cp -R pages/* void-tech/src/pages/docs/
          cd void-tech
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Sync pages"
          git push https://${API_TOKEN_GITHUB}@github.com/cozy-creator/void-tech.git dev
